### ISSUE TITLE
Logging in from januslinjeforening.no does not work

### ISSUE THREAD

**Issue by ankile** [rubberdok/indok-web#1466]
## Describe the bug

The IdPorten/Feide connection is refused when the hostname is januslinjeforening.no, so one can only log in from indokntnu.no.

## To Reproduce

1. Go to [januslinjefornening.no](https://januslinjeforening.no/)
2. Press the log in button in the top right
3. See the connection refused-thingy-thing

## Expected behavior

I should have been taken to the Feide login page.

## Desktop (please complete the following information):

- OS: MacOS
- Browser Chrome
- Version Unknown

**Comment by MagnusHafstad** [comment]
This was a larger problem when there was a link to it. Now this problem is too niche for us to fix as it is almost impossible to find by accident.
