### ISSUE TITLE
⏫ chore(deps): bump MUI to v5

### ISSUE THREAD

**Issue by TechedLemur** [rubberdok/indok-web#290]
If you want to use the newest versions of MUI components and continue getting updates, there are some breaking changes.
With the release of v5, the npm organization name (scope) has moved from @material-ui to @mui.
That means all the imports needs to be changed.

Read more about the change [here](https://mui.com/blog/material-ui-is-now-mui/).

**Comment by larwaa** [comment]
Work is already underway (DOK-219), yet some adjustments remain.
