### ISSUE TITLE
Countdown timer drifts significantly before event signup opens

### ISSUE THREAD

**Issue by patrikkj** [rubberdok/indok-web#427]
## Describe the bug

When waiting for an event to open, the countdown timer consistently drifts about 1 second per minute (the timer counts down _slower_ than one would expect).  

## To Reproduce

1. Go to [an arbitrary event](https://indokntnu.no/events/41) with time-bound registration. 
2. Start a stopwatch.
3. Grab a coffee ☕️☕️☕️
4. Quick maths

## Proposed solution

The idea is to trust the system time (as it is accurate), but rather asserting for every incremental update that the system time hasn't been tampered with.

Run the snippet below to see how it works!

```javascript
// Let's assume that the server-to-client delay is negligible
let serverTime = Date.now() - Math.random();

// This represents our best estimate of the current server time - we'll use system time to do updates
let currentServerTime = serverTime;

// Let's use the system time to do verification and calculate time deltas only
let systemTimePrev = Date.now();
let systemTimeCurrent;
let systemTimeDelta;

const cb = () => {
    systemTimeCurrent = Date.now();

    // Simulate tinkering with the system time with a prob. of 3% per frame
    if (Math.random() < 0.03) {
        console.log("Kødder litt med klokka ... ");
        systemTimeCurrent = systemTimeCurrent - 1000;
    }
    
    // Infer the time difference since last frame render
    systemTimeDelta = systemTimeCurrent - systemTimePrev;
    if (systemTimeDelta < 0) {
        // Gutta fucka med klokka
        console.error("Ikke greit! 😡");
        return
    } else {
        // Update the current server time estimate
        currentServerTime = currentServerTime + systemTimeDelta;
        systemTimePrev = systemTimeCurrent;
        console.log("currentServerTime = " + currentServerTime);
    }

    // https://www.ntnu.no/wiki/display/itgk/Rekursive+funksjoner
    requestAnimationFrame(cb)
}

// `Window.requestAnimationFrame(callback)` is used to request a 
//     callback to be invoked before the next frame repaint.
// We pass it a recursive callback which requests a re-invocation 
//     of itself such that it is re-invoked before every single frame render.
requestAnimationFrame(cb)
```

**Comment by larwaa** [comment]
Users manipulating their system time to "cheat" the system is not a concern as we run server side validation after #117

**Comment by patrikkj** [comment]
> Users manipulating their system time to "cheat" the system is not a concern as we validate server side after #117

Nice! 

The main point is to revolve the issue of time drift, as in the current case if you navigate to the event page a while before registration opens you will be presented with the ability to register several seconds after the registrations actually opens. The validation checking if the difference is negative is just a simple check to identify if the has been tampered with. I think this should just trigger some silent logging to the database, as it may happen for legitimate reasons (e.g. sync triggered by the OS). 

By hooking this callback to frame rendering (occurs about once every 15-20 milliseconds, depends on your configuration) is a simple way to make sure that the rendered time is always up to date. Executing a few lines of logic once per frame render should take a few nanoseconds at most.
