### ISSUE TITLE
Får ikke laget arrangement som kurs, kun som fest på nettsiden

### ISSUE THREAD

**Issue by oskargaso** [rubberdok/indok-web#903]
## Describe the bug

Prøvde å lage et arrangement under kategorien kultur, men da dukket det ikke opp etterpå. Sjekket at jeg ikke hadde på noen filter eller liknende som skjulte det.

**Comment by larwaa** [comment]
Heisann! Sånn skal det jo ikke være. Hadde vært supert med litt mer info:
- Har du forsøkt flere ganger?
- Får du noen feilmeldinger?
- Navn på arrangementet
- Hvilken organisasjon som skal ha arrangementet
- Gjerne skjermdump av informasjonen du prøver å legge inn for arrangementet når det feiler.

**Comment by larwaa** [comment]
Lukker denne siden vi ikke kan reprodusere feilen, og vi ikke har fått mer informasjon om problemet. Si gjerne ifra dersom problemet vedvarer.
